### ISSUE TITLE
How to work with reference styled hyperlinks?

### ISSUE THREAD

**Issue by jaythamke** [six-two/mkdocs-badges#1]
We adopt the reference styled hyperlinks for certain reasons. I would like to know how mkdocs-badges plugin can be used with such referenced styled links. 

See the example below. 

```
|t:More Info|v:See more info|l:more_info|

[more_info]: https://www.example.com
```

Please provide the working example.

Thanks
Jayesh

P.S. The example does not work.

**Comment by six-two** [comment]
Hi Jayesh,

I don't currently support reference style links. A workaround may be to just use `mkdocs-badges` to render the badge and use the badge in a normal markdown link. It would look something like this:

```
[
|t:More Info|v:See more info| 
][more_info]

[more_info]: https://www.example.com
```

The markdown looks pretty ugly and the badge is not underlined when it is hovered, but it should work.

However, I plan on doing a few (breaking) changes to the badge syntax to add support for CSS classes and make it more easy to understand. When doing these changes I will think about, if I can easily add reference style links.

BR
six-two

**Comment by jaythamke** [comment]
I would highly appreciate the update.
Thanks and best regards,
Jayesh

**Comment by six-two** [comment]
Reference link badges are now supported in version 0.3.0. See section "Reference link badges" on the [badges page](https://mkdocs-badges.six-two.dev/badges/). However since the badge formats changed you may need to update existing badges manually. See the [migration page](https://mkdocs-badges.six-two.dev/migration/).
